apiVersion: v1
kind: Pod
metadata:
  name: aplicacao
spec:
  containers:
    - name: container-minikube-helloworld
      image: idasilva/minikube-helloworld:2.0
      ports:
        - containerPort: 8080

