apiVersion: v1
kind: Pod
metadata:
  name: aplicacao
spec:
  containers:
    - name: container-minikube-helloword
      image: idasilva/minikube-helloword:1.0
      ports:
        - containerPort: 80

